name: api_doc_parser
description: Dart library to parse OpenAPI documentations.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies: 
  freezed_annotation: ^1.0.0
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^1.0.0
  json_serializable: ^6.1.1
  test: ^1.19.2
  very_good_analysis: ^2.4.0
