include: package:very_good_analysis/analysis_options.2.4.0.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "bin/cache/**"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false