name: bot
description: Command Line Interface for Flutter
version: 0.0.1
publish_to: none
homepage: https://github.com/herveGuigoz/bot

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies: 
  args: ^2.3.0
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  io: ^1.0.3
  json_annotation: ^4.4.0
  path: ^1.8.0
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.3
  test: ^1.19.2
  very_good_analysis: ^2.4.0

executables:
  bot: